---
- name: install httpd on centos 7
  package: name=httpd state=present
  when: ansible_os_family == "Redhat"

- name: install apache2 on ubuntu
  package: name=apache2 state=present
  when: ansible_os_family == "Debian"

- name: edit conf file in centos 7
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  when: ansible_os_family == "Redhat"

- name: edit conf file in ubuntu
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
  when: ansible_os_family == "Debian"

- name: start the http service in centos 
  service: name=httpd state=started enabled=yes
  when: ansible_os_family == "Redhat"

- name: start apache2 service in ubuntu
  service: name=apache2 state=started 



